version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${VOL_CERTS}:/etc/nginx/certs:ro
      - ${VOL_VHOSTD}:/etc/nginx/vhost.d
      - ${VOL_HTML}:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOL_CERTS}:/etc/nginx/certs:rw
      - ${VOL_VHOSTD}:/etc/nginx/vhost.d
      - ${VOL_HTML}:/usr/share/nginx/html

  launcher:
    image: nginx
    container_name: launcher
    restart: always
    expose:
      - "80"
    volumes:
      - ./launcher:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=${DOMAIN},www.${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

  curso-${COURSE_1_NAME}:
    image: curso:base
    build:
      context: .
    container_name: curso-${COURSE_1_NAME}
    restart: always
    ports:
      - "${COURSE_1_PORT}:3000"
    volumes:
      - ./cursos/${COURSE_1_NAME}:/usr/local/docsify
    environment:
      - VIRTUAL_HOST=${COURSE_1_NAME}.${DOMAIN},www.${COURSE_1_NAME}.${DOMAIN}
      - LETSENCRYPT_HOST=${COURSE_1_NAME}.${DOMAIN},www.${COURSE_1_NAME}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

  curso-${COURSE_2_NAME}:
    image: curso:base
    container_name: curso-${COURSE_2_NAME}
    restart: always
    ports:
      - "${COURSE_2_PORT}:3000"
    volumes:
      - ./cursos/docker:/usr/local/docsify
    environment:
      - VIRTUAL_HOST=${COURSE_2_NAME}.${DOMAIN},www.${COURSE_2_NAME}.${DOMAIN}
      - LETSENCRYPT_HOST=${COURSE_2_NAME}.${DOMAIN},www.${COURSE_2_NAME}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
 
  curso-${COURSE_3_NAME}:
    image: curso:base
    container_name: curso-${COURSE_3_NAME}
    restart: always
    ports:
      - "3003:3000"
    volumes:
      - ./cursos/${COURSE_3_NAME}:/usr/local/docsify
    environment:
      - VIRTUAL_HOST=${COURSE_3_NAME}.${DOMAIN},www.${COURSE_3_NAME}.${DOMAIN}
      - LETSENCRYPT_HOST=${COURSE_3_NAME}.${DOMAIN},www.${COURSE_3_NAME}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

volumes: 
  certs:
  html:
  vhostd:
