---

- hosts: web
  name: Run compose
  tasks:
    - include_vars: ../vars.yml
    - include_tasks: ../tasks/task_clone_repo.yml
    - include_tasks: ../tasks/task_restart_compose.yml
    - include_tasks: ../tasks/task_delete_env.yml

...
