on:
  push:
    branches:
      - master

name: Pull repo
jobs:
  pull-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Run a command remotely
      uses: docker://evaneos/ssh-action:0.1.0
      with:
        hosts: ${{ secrets.PULL_REPO_HOST }}
        user: ${{ secrets.PULL_REPO_USER }}
        private_key: ${{ secrets.PULL_REPO_PRIVATE_KEY }}
        commands: |
          cd ~/formacion
          git pull
